# Generated by Django 4.2.1 on 2023-12-18 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('electronic_journal', '0002_alter_user_group'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userquest',
            options={'verbose_name': 'Готовая работа', 'verbose_name_plural': 'Готовые работы'},
        ),
        migrations.AlterField(
            model_name='quest',
            name='date_added',
            field=models.DateField(auto_now_add=True, verbose_name='Дата Добавления'),
        ),
    ]
