# Generated by Django 4.2.1 on 2023-12-18 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('electronic_journal', '0003_alter_userquest_options_alter_quest_date_added'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userquest',
            name='slug',
            field=models.SlugField(blank=True, max_length=100, null=True, unique=True, verbose_name='URL'),
        ),
    ]
